-- MySQL Script generated by MySQL Workbench
-- Thu Feb 15 14:43:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mechanicalworkshopdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mechanicalworkshopdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mechanicalworkshopdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mechanicalworkshopdb` ;

-- -----------------------------------------------------
-- Table `mechanicalworkshopdb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshopdb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mechanicalworkshopdb`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshopdb`.`mecanico` (
  `id_mecanico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `especialidade` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_mecanico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mechanicalworkshopdb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshopdb`.`veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(10) NULL DEFAULT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  `ano` INT NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_veiculo`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `veiculo_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mechanicalworkshopdb`.`cliente` (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mechanicalworkshopdb`.`ordemservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshopdb`.`ordemservico` (
  `id_os` INT NOT NULL AUTO_INCREMENT,
  `data_emissao` DATE NULL DEFAULT NULL,
  `valor_total` DECIMAL(10,2) NULL DEFAULT NULL,
  `status` ENUM('Pendente', 'Em Andamento', 'Concluído') NULL DEFAULT NULL,
  `data_conclusao` DATE NULL DEFAULT NULL,
  `id_veiculo` INT NULL DEFAULT NULL,
  `id_mecanico` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_os`),
  INDEX `id_veiculo` (`id_veiculo` ASC) VISIBLE,
  INDEX `id_mecanico` (`id_mecanico` ASC) VISIBLE,
  CONSTRAINT `ordemservico_ibfk_1`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `mechanicalworkshopdb`.`veiculo` (`id_veiculo`),
  CONSTRAINT `ordemservico_ibfk_2`
    FOREIGN KEY (`id_mecanico`)
    REFERENCES `mechanicalworkshopdb`.`mecanico` (`id_mecanico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mechanicalworkshopdb`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshopdb`.`servico` (
  `id_servico` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mechanicalworkshopdb`.`os_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshopdb`.`os_servico` (
  `id_os` INT NOT NULL,
  `id_servico` INT NOT NULL,
  PRIMARY KEY (`id_os`, `id_servico`),
  INDEX `id_servico` (`id_servico` ASC) VISIBLE,
  CONSTRAINT `os_servico_ibfk_1`
    FOREIGN KEY (`id_os`)
    REFERENCES `mechanicalworkshopdb`.`ordemservico` (`id_os`),
  CONSTRAINT `os_servico_ibfk_2`
    FOREIGN KEY (`id_servico`)
    REFERENCES `mechanicalworkshopdb`.`servico` (`id_servico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mechanicalworkshopdb`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshopdb`.`peca` (
  `id_peca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `id_os` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_peca`),
  INDEX `id_os` (`id_os` ASC) VISIBLE,
  CONSTRAINT `peca_ibfk_1`
    FOREIGN KEY (`id_os`)
    REFERENCES `mechanicalworkshopdb`.`ordemservico` (`id_os`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
